//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TQI.ControlCenter.Logic.NBAScrapping {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://TQI.Scrape.NBA.ServiceScheduler", ConfigurationName="NBAScrapping.INBAScrapingContract")]
    public interface INBAScrapingContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TQI.Scrape.NBA.ServiceScheduler/INBAScrapingContract/GetProgress", ReplyAction="http://TQI.Scrape.NBA.ServiceScheduler/INBAScrapingContract/GetProgressResponse")]
        int GetProgress(string providerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TQI.Scrape.NBA.ServiceScheduler/INBAScrapingContract/GetProgress", ReplyAction="http://TQI.Scrape.NBA.ServiceScheduler/INBAScrapingContract/GetProgressResponse")]
        System.Threading.Tasks.Task<int> GetProgressAsync(string providerName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INBAScrapingContractChannel : TQI.ControlCenter.Logic.NBAScrapping.INBAScrapingContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NBAScrapingContractClient : System.ServiceModel.ClientBase<TQI.ControlCenter.Logic.NBAScrapping.INBAScrapingContract>, TQI.ControlCenter.Logic.NBAScrapping.INBAScrapingContract {
        
        public NBAScrapingContractClient() {
        }
        
        public NBAScrapingContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NBAScrapingContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NBAScrapingContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NBAScrapingContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetProgress(string providerName) {
            return base.Channel.GetProgress(providerName);
        }
        
        public System.Threading.Tasks.Task<int> GetProgressAsync(string providerName) {
            return base.Channel.GetProgressAsync(providerName);
        }
    }
}
